export const SERVICE_PAGES = Object.freeze([
  Object.freeze({
    slug: 'manutencao-caminhoes',
    href: '/servicos/manutencao-caminhoes',
    cardTitle: 'Caminhões e máquinas pesadas',
    featured: true,
    ticketCategory: 'trucks',
    relatedSlugs: ['central-concreto', 'reforma-chassis'],
    title: 'Manutenção de caminhões em Itajaí | CKF Manutenção',
    heading: 'Manutenção de caminhões e máquinas pesadas em Itajaí',
    eyebrow: 'Caminhões e máquinas pesadas',
    description: 'Manutenção preventiva e corretiva para caminhões e máquinas pesadas em Itajaí. Diagnóstico, freios, suspensão, hidráulica, solda e reparos com a CKF.',
    intro: 'Quando caminhão ou máquina para, a operação sente na hora. A CKF atua em diagnóstico, manutenção e reparos para devolver segurança e previsibilidade ao trabalho.',
    image: '/assets/real/chassis-real.webp',
    imageAlt: 'Caminhão em atendimento de manutenção na CKF',
    ctaService: 'manutenção de caminhões e máquinas pesadas',
    services: [
      ['Preventiva e revisão', 'Inspeção de itens críticos para antecipar desgaste e reduzir paradas inesperadas.'],
      ['Suspensão e freios', 'Avaliação e reparo dos sistemas ligados à estabilidade e à segurança do veículo.'],
      ['Hidráulica e embreagem', 'Diagnóstico e manutenção de componentes essenciais à operação pesada.'],
      ['Solda e reparos estruturais', 'Correções e reforços executados conforme a necessidade identificada no equipamento.'],
    ],
  }),
  Object.freeze({
    slug: 'central-concreto',
    href: '/servicos/central-concreto',
    cardTitle: 'Centrais de concreto',
    featured: true,
    ticketCategory: 'concrete_plants',
    relatedSlugs: ['manutencao-caminhoes', 'estruturas-metalicas'],
    title: 'Manutenção de centrais de concreto em Itajaí | CKF Manutenção',
    heading: 'Manutenção de centrais de concreto em Itajaí',
    eyebrow: 'Centrais de concreto',
    description: 'Manutenção de centrais de concreto em Itajaí com atuação em equipamentos, estruturas, solda e componentes mecânicos. Solicite avaliação à CKF.',
    intro: 'Central de concreto exige continuidade. A CKF atende necessidades de manutenção e recuperação em equipamentos e estruturas para reduzir incerteza e colocar a operação novamente em ritmo.',
    image: '/assets/central-concreto-editorial.webp',
    imageAlt: 'Central de concreto atendida pela CKF Manutenção',
    ctaService: 'manutenção de centrais de concreto',
    services: [
      ['Manutenção preventiva', 'Inspeção e intervenção programada em pontos de desgaste da operação.'],
      ['Reparos mecânicos', 'Avaliação de componentes e correção de falhas conforme o diagnóstico em campo.'],
      ['Solda e caldeiraria', 'Reparos e reforços em componentes e estruturas metálicas da central.'],
      ['Recuperação de equipamentos', 'Soluções para prolongar a vida útil de conjuntos que ainda podem voltar ao trabalho.'],
    ],
  }),
  Object.freeze({
    slug: 'reforma-chassis',
    href: '/servicos/reforma-chassis',
    cardTitle: 'Reforma de equipamentos e chassis',
    featured: true,
    ticketCategory: 'chassis',
    relatedSlugs: ['manutencao-caminhoes', 'estruturas-metalicas'],
    title: 'Reforma de chassis em Itajaí | CKF Manutenção',
    heading: 'Reforma de chassis em Itajaí',
    eyebrow: 'Recuperação estrutural',
    description: 'Reforma e recuperação de chassis em Itajaí. Avaliação estrutural, solda, reforços, recuperação e acabamento para equipamentos de trabalho pesado.',
    intro: 'Desgaste estrutural pede mais do que acabamento. A CKF avalia a condição do conjunto e executa a recuperação necessária para devolver integridade e vida útil ao equipamento.',
    image: '/assets/real/maquina-pesada-real.webp',
    imageAlt: 'Equipamento pesado em processo de recuperação pela CKF',
    ctaService: 'reforma e recuperação de chassis',
    services: [
      ['Avaliação estrutural', 'Leitura do estado do chassis e identificação dos pontos que exigem intervenção.'],
      ['Solda e reforços', 'Recuperação dos pontos comprometidos conforme a necessidade técnica encontrada.'],
      ['Adaptações e recuperação', 'Execução de ajustes e reparos para devolver funcionalidade ao conjunto.'],
      ['Pintura e acabamento', 'Proteção e finalização depois da etapa estrutural e dos testes do serviço.'],
    ],
  }),
  Object.freeze({
    slug: 'estruturas-metalicas',
    href: '/servicos/estruturas-metalicas',
    cardTitle: 'Estruturas metálicas',
    featured: true,
    ticketCategory: 'metal_structures',
    relatedSlugs: ['central-concreto', 'reforma-chassis'],
    title: 'Estruturas metálicas e solda em Itajaí | CKF Manutenção',
    heading: 'Estruturas metálicas e solda em Itajaí',
    eyebrow: 'Estruturas e fabricação',
    description: 'Serviços de estruturas metálicas, solda, reforços e fabricação em Itajaí para operações industriais e equipamentos pesados. Fale com a CKF.',
    intro: 'Estrutura bem executada precisa nascer do uso real que terá em campo. A CKF combina leitura técnica, solda e fabricação para reparar, reforçar ou construir soluções para a operação.',
    image: '/assets/estruturas-editorial.webp',
    imageAlt: 'Estrutura metálica executada em ambiente industrial',
    ctaService: 'estruturas metálicas e solda',
    services: [
      ['Solda e reparos', 'Correção de pontos danificados em estruturas e componentes metálicos.'],
      ['Reforços estruturais', 'Intervenções para recuperar ou aumentar a robustez de conjuntos existentes.'],
      ['Fabricação', 'Execução de soluções metálicas conforme a necessidade apresentada pela operação.'],
      ['Ajustes em campo', 'Atuação orientada ao encaixe, funcionamento e condição real do equipamento.'],
    ],
  }),
])
